apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bot
  name: bot
  namespace: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: "{{ REGISTRY }}/{{ REPOSITORY }}:{{ IMAGE_TAG }}"
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot
                  key: token
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
