name: cicd

on:
  push:
    branches:
      - main

jobs:
  cicd:
    name: cicd
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: terraform setup
        uses: hashicorp/setup-terraform@v2

      - name: terraform run
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: kubectl setup
        uses: tale/kubectl-action@v1

      - name: kubectl run
        working-directory: kubernetes
        run: |
          aws eks --region us-west-1 update-kubeconfig --name eks
          kubectl create namespace example-app --dry-run=client -o yaml | kubectl apply -f -
          for file in $(find . -name '*.yml' -or -name '*.yaml'); do kubectl apply -n example-app -f $file; done
