name: cicd
on:
  push:
    tags:
      - "*.*.*"
jobs:
  docker: # This is temporary: We should use ECR.
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: docker/setup-buildx-action@v2
      - name: credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: apply
        uses: docker/build-push-action@v3
        with:
          context: app
          push: true
          tags: wjmolina/tmp:${{ github.ref_name }},wjmolina/tmp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  terraform:
    name: terraform
    needs: docker
    runs-on: ubuntu-latest
    outputs:
      eks_name: ${{ steps.apply.outputs.eks_name }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: apply
        id: apply
        run: |
          terraform init
          terraform apply -auto-approve
          echo ::set-output name=eks_name::$(terraform output aws_eks_cluster_eks_name | tr -d '"')
  kubernetes:
    name: kubernetes
    needs: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kubernetes
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: setup
        uses: tale/kubectl-action@v1
      - name: jinja
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: deployments/deployment.yml
          output_file: deployments/deployment.yml
        env:
          IMAGE_TAG: ${{ github.ref_name }}
      - name: apply
        run: |
          aws eks --region us-west-1 update-kubeconfig --name ${{ needs.terraform.outputs.eks_name }}
          kubectl create namespace example-app --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -R -f .
