name: cicd
on:
  push:
    tags:
      - "*.*.*"
jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      eks_name: ${{ steps.set-outputs.outputs.eks_name }}
      ecr_name: ${{ steps.set-outputs.outputs.ecr_name }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: set outputs
        id: set-outputs
        run: |
          echo ::set-output name=eks_name::$(terraform output eks_name | tr -d '"')
          echo ::set-output name=ecr_name::$(terraform output ecr_name | tr -d '"')

  docker:
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        working-directory: app
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: login
        id: login
        uses: aws-actions/amazon-ecr-login@v1

      - name: push
        env:
          REGISTRY: ${{ steps.login.outputs.registry }}
          REPOSITORY: ${{ needs.terraform.outputs.eks_name }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  kubernetes:
    name: kubernetes
    needs: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kubernetes
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: setup
        uses: tale/kubectl-action@v1

      - name: jinja
        uses: jayamanikharyono/jinja-action@v0.1
        with:
          data: IMAGE_TAG=${{ github.ref_name }} -D BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          path: kubernetes/**/*.yml

      - name: apply
        run: |
          aws eks --region us-west-1 update-kubeconfig --name ${{ needs.terraform.outputs.eks_name }}
          kubectl apply -R -f .
