name: deployment
on:
  push:
    branches:
      - main
jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # - name: login
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: setup buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: push build
      #   uses: docker/build-push-action@v2
      #   with:
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
  terraform:
    name: terraform
    needs: docker
    runs-on: ubuntu-latest
    outputs:
      aws_eks_cluster_eks_name: ${{ steps.output.outputs.aws_eks_cluster_eks_name }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve
      - name: output
        working-directory: terraform
        run: echo "::set-output name=aws_eks_cluster_eks_name::eks"
  kubernetes:
    name: kubernetes
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: setup kubectl
        uses: tale/kubectl-action@v1
      - name: apply
        working-directory: kubernetes
        run: |
          aws eks --region us-west-1 update-kubeconfig --name ${{ needs.terraform.outputs.aws_eks_cluster_eks_name }}
          kubectl create namespace example-app --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -R -f kubernetes
