name: deployment
on:
  push:
    tags:
      - *.*.*
jobs:
  # This is temporary: We should use ECR.
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: command
        uses: ${{ github.ref_name }}
      # - name: TODO
      #   uses: docker/setup-qemu-action@v2
      # - name: TODO
      #   uses: docker/setup-buildx-action@v2
      # - name: TODO
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: TODO
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: wjmolina/tmp:latest
  terraform:
    name: terraform
    needs: docker
    runs-on: ubuntu-latest
    outputs:
      eks_name: ${{ steps.apply.outputs.eks_name }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: apply
        id: apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve
          echo ::set-output name=eks_name::$(terraform output aws_eks_cluster_eks_name | tr -d '"')
  kubernetes:
    name: kubernetes
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: setup
        uses: tale/kubectl-action@v1
      - name: apply
        working-directory: kubernetes
        run: |
          aws eks --region us-west-1 update-kubeconfig --name ${{ needs.terraform.outputs.eks_name }}
          kubectl create namespace example-app --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -R -f .
