name: docker
on:
  push:
    tags:
      - "*.*.*"
  workflow_run:
    workflows:
      - terraform
    types:
      - completed
jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: app
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: login
        id: login
        uses: aws-actions/amazon-ecr-login@v1

      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-artifact

      - name: push
        env:
          REGISTRY: ${{ steps.login.outputs.registry }}
          REPOSITORY: $(cat terraform-artifact | grep ECR_NAME | grep -o '[^=]*$')
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
