name: k8s

on:
  push:
    branches:
      - main

jobs:
  k8s:
    name: k8s
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: create ns example-app
