name: k8s

on:
  push:
    branches:
      - main

jobs:
  k8s:
    name: k8s
    runs-on: ubuntu-latest
    steps:
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl get pods
