name: cicd
on: push # CHANGE THIS
jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: setup
        uses: hashicorp/setup-terraform@v2
      - name: apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-artifact
          path: terraform-artifact
