name: test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          pip install jinja2-cli
          dir=`ls kubernetes/**/*.yml`
          for eachfile in $dir;
          do
            jinja2 --strict \
              -D BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -D REGISTRY=${{ steps.ecr-login.outputs.registry }} \
              -D REPOSITORY=${{ needs.terraform.outputs.eks_name }} \
              -D IMAGE_TAG=${{ github.ref_name }} \
            $eachfile > $eachfile
          done
          cat $eachfile
